version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

workflows:
  build-unity-project:
    jobs:
      # Create the Unity activation license file
      # You only need this if you are using the Personal license
      # More info: https://game.ci/docs/circleci/activation#personal-license
      - unity/create-activation-file:
          name: "create-activation-file"

      # Run tests in playmode for Linux, Windows and macOS
      # More info: https://game.ci/docs/circleci/test

      # Build for several other platforms
      - unity/build:
          name: "build-webgl"
          step-name: "Build WebGL"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "webgl"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: "WebGL"
          # Since "Compression Format" is set to disabled in Unity,
          # if we set "compress" to false, we can play the game from
          # the CircleCI web app by going in the "Artifacts" tab.
          compress: false
          context: unity
          post-steps:
            - run:
                name: Creating Artifact Directory
                command: |
                  echo "my artifact file" > /tmp/art-1;
                  mkdir /tmp/artifacts;
                  echo "my artifact files in a dir" > /tmp/artifacts/art-2;
            - store_artifacts:
                path: /tmp/art-1
                destination: artifact-file
            - store_artifacts:
                path: /tmp/artifacts